apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-app
  labels:
    app: prediction-test-app
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: prediction-test-app  
  template:
    metadata:
      labels:
        app: prediction-test-app  
    spec:
      containers:
      - name: prediction-app1
        image: prediction-app1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000   
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-app
spec:
  selector:
    app: prediction-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
